;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Damage.Reflect",NewTagName="Damage.NoReflect")
+GameplayTagList=(Tag="Action.Attacking",DevComment="")
+GameplayTagList=(Tag="Action.Sprinting",DevComment="")
+GameplayTagList=(Tag="Damage.NoReflect",DevComment="Used by reflect damage sources such as thorns, mainly to prevent re-reflect damage")
+GameplayTagList=(Tag="Keycard.Blue",DevComment="")
+GameplayTagList=(Tag="Keycard.Red",DevComment="")
+GameplayTagList=(Tag="Keycard.Yellow",DevComment="")
+GameplayTagList=(Tag="Status.Burning",DevComment="")
+GameplayTagList=(Tag="Status.Parrying",DevComment="")

